### ISSUE TITLE
前端/框架通识/Proxy 与 Obeject.defineProperty 对比

### ISSUE THREAD

**Issue by sophiayang1997** [InterviewMap/InterviewMap#103]
第一句
【Obeject.defineProperty 虽然已经能够实现双向绑定了，但是他还是有缺陷的。】=>
【Object.defineProperty 虽然已经能够实现双向绑定了，但是他还是有缺陷的。】

Object笔误了吧？

**Comment by timeTravelCYN** [comment]
@sophiayang1997 
确实笔误了，谢谢指出！
