### ISSUE TITLE
Typo error：CommonJS and ES6

### ISSUE THREAD

**Issue by csuZipple** [InterviewMap/InterviewMap#105]
At：（In Chinese Version）
Module：CommonJS
The differences between the modularizations in CommonJS and in ES6 are：
> 前者是同步导入，因为用于服务端，文件都在本地，同步导入即使卡住主线程影响也不大。而后者是异步导入，因为用于浏览器，需要下载文件，如果也采用导入会对渲染有很大影响
missing words : 同步（导入）

**Comment by naihe138** [comment]
@csuZipple 谢谢您的仔细阅读并指出，鉴于严谨性，确实是少了`同步`二字。我们会尽快修正。
