### ISSUE TITLE
你好，这里Vue- NextTick 原理分析一节中的“所以在新版本中，会默认使用 microtasks，但在特殊情况下会使用 macrotasks，比如 v-on。”是不是有点问题呢

### ISSUE THREAD

**Issue by Huanqiang** [InterviewMap/InterviewMap#106]
<img width="864" alt="image" src="https://user-images.githubusercontent.com/7790051/43941280-13bd0b38-9ca6-11e8-98f0-5d4ea5d2ddcd.png">

**Comment by timeTravelCYN** [comment]
@Huanqiang  请问您觉得问题是什么呢？ [next-tick](https://github.com/vuejs/vue/blob/dev/src/core/util/next-tick.js#L26)，根据源码来看确实是默认使用 `microtasks`，特殊情况使用 `macrotasks`

**Comment by Huanqiang** [comment]
抱歉，今天才看到这个回复，确实是我的不仔细，我把特殊情况的 macrotasks  看成了 microtasks。实在抱歉，打扰了...
