### ISSUE TITLE
浏览器->事件机制中事件捕获和冒泡的源头应该是window

### ISSUE THREAD

**Issue by Jerry12138** [InterviewMap/InterviewMap#119]
有个疑问，Document 对象是 Window 对象的一部分，给window和document都绑定事件，点击时会先触发window上的事件再触发document上的事件，所以个人认为事件捕获和冒泡的源头应该是window，望解惑，谢谢。

**Comment by naihe138** [comment]
@Jerry12138 是的，这里有解惑哦[https://www.w3.org/TR/DOM-Level-3-Events/#dom-event-architecture](https://www.w3.org/TR/DOM-Level-3-Events/#dom-event-architecture)
