### ISSUE TITLE
事件触发三阶段,描述似乎有误

### ISSUE THREAD

**Issue by 1391020381** [InterviewMap/InterviewMap#65]
window.addEventListener('click',(event) =>{
	console.log('冒泡')
},false);
window.addEventListener('click',(event) =>{
	console.log('捕获 ')
},true)

chrome 版本  ：67.03396.62

执行结果：
![addeventlistener](https://user-images.githubusercontent.com/24850842/42980489-2c880c64-8c0a-11e8-98c6-2882a080e930.png)

**Comment by KieSun** [comment]
```html
<body>
  <div class="test1">
    test1
    <div class="test2">
      test2
    </div>
  </div>
  <script>
    let t1 = document.querySelector('.test1')
    let t2 = document.querySelector('.test2')
    t1.addEventListener('click',function(event){
        console.log('s1冒泡');
    },false);
    t1.addEventListener('click',function(event){
        console.log('s1捕获');
    },true);
    t2.addEventListener('click',function(event){
        console.log('s2冒泡');
    },false);
    t2.addEventListener('click',function(event){
        console.log('s2捕获 ');
    },true);
  </script>
</body>
```
chrome 版本 ：67.0.3396.99

当你点击 test1 时，会打印
```js
s1冒泡
s1捕获
```

当你点击 test2 时，会打印
```js
s1捕获
s2冒泡
s2捕获 
s1冒泡
```

以上结果符合文章中描述的：如果给一个目标节点同时注册冒泡和捕获事件，事件触发会按照注册的顺序执行。

**Comment by 1391020381** [comment]
我想问下，你复制我的代码到 Chrome控制台执行的话，是会先打印捕获？这个是什么原因？是我哪里理解错误？

**Comment by naihe138** [comment]
@1391020381  你的没有错，对于`window` 和 `document`对象，确实如你的结果一样。

**Comment by 1391020381** [comment]
@naihe138  似乎对window和 dom根节点处理不同。
