### ISSUE TITLE
JS simulate bind seem not right

### ISSUE THREAD

**Issue by MrZhang123** [InterviewMap/InterviewMap#67]
## Link
https://yuchengkai.cn/docs/zh/frontend/#%E6%A8%A1%E6%8B%9F%E5%AE%9E%E7%8E%B0-call-%E5%92%8C-apply
## Describe

In this section , simulate `bind`:

```JS
Function.prototype.myBind = function (context) {
  if (typeof this !== 'function') {
    throw new TypeError('Error')
  }
  var _this = this
  var args = [...arguments].slice(1)
  // return a function
  return function F() {
    // we can use `new F()` because it returns a function, so we need to determine
    if (this instanceof F) {
      return new _this(args, ...arguments)
    }
    return _this.apply(context, args.concat(arguments))
  }
}
```
### Test code:

```js
function Point(x, y, a, b, c) {
  this.x = x;
  this.y = y;
}

var p = new Point(1, 2);
var YAxisPoint = Point.myBind(null, 1);
var axisPoint = new YAxisPoint(5);
console.log(axisPoint);
```

#### result:
```js
{
  x: [1],
  y: 5
}
```
#### expect:
```js
{
  x: 1,
  y: 5
}
```

### Analysis

In `return new _this(args, ...arguments)` may not right , because `var args = [...arguments].slice(1)` is an Array and  it will not spread automatic. It need to spread, so code may change like this:

```js
return new _this(...args, ...arguments)
```
### pull request

https://github.com/InterviewMap/InterviewMap/pull/66

**Comment by KieSun** [comment]
Thanks for your PR!

**Comment by SabinDiwan** [comment]
Thank u somuch sir.if i can only figure out which conversation im in
rightnow.using notepad5 maybe.exhausted phone.working at its best.if i gota
u right.gotta!but still would help if the begining of the conversation
shows so i can figure out which box im working in now.thanks
