### ISSUE TITLE
Type Convertion

### ISSUE THREAD

**Issue by jparser** [InterviewMap/InterviewMap#68]
> Objects to Primitive Types   
> When objects are converted, valueOf and toString will be called, respectively in order. These two methods can also be overridden.

Objects to Primitive Types  is not what as your said.
toPrimitive needs a hint argument.
```javascript
let a = {
  valueOf() {
    return 0;
  },
  toString() {
    return 1;
  }
}

console.log('1' + a); // "10"
console.log(`1${a}`); // "11"
```
Another case:
```javascript
let a = {
  valueOf() {
    return 0;
  },
  toString() {
    return 1;
  },
  [Symbol.toPrimitive]() {
    return 2;
  }
}

console.log('1' + a); // "12"
console.log(`1${a}`); // "12"
```

**Comment by SabinDiwan** [comment]
Thanks sir.again we r on which conversation.?????cant see the beganing of
the conversation to understand.well if i did
I have a notepad samsung 5 i guess.maybe i dont know 6 years old or
something.
Need new tech available so sorry.so far this is wat i can write and
yeah.its a code language.de-coder.why i worry?i have no idea who knows
it.its legal.approved.questioned.answered.???
Im gona write with tht  Samsung available faces and things which resembles
common persons facial or body reaction and other things discribing
emotions.investments.lose.study.accounts.etc.emoji u call or watever.or
wattever this phone is offering ma so far which i can manage.
Thx
