### ISSUE TITLE
'\w'	alphanumeric characters, underline character or Chinese characters

### ISSUE THREAD

**Issue by jparser** [InterviewMap/InterviewMap#69]
No Chinese characters

**Comment by jparser** [comment]
@KieSun 
Sorry, i did not descript it clearly.
In RegExp character class `\w` does not in include *Chinese characters*

[Mozilla character-classes：](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#character-classes)
> Matches any alphanumeric character from the basic Latin alphabet, including the underscore. Equivalent to [A-Za-z0-9_].

[ECMAScript sepc](https://tc39.github.io/ecma262/#sec-runtime-semantics-wordcharacters-abstract-operation)

**Comment by SabinDiwan** [comment]
So what.u cant decode if its  written in short span.multitask.MULTI
CODES.Ur best system cant get it?

Just recieved another CASE.HELP ME.CARE.
THTS WAT IT WAS.senior citizen.
GOTTA ANSWER THT.
Hey thx.ill post a nother piece shortly.between multitask.
Thx.fe aman allah
