### ISSUE TITLE
对浅拷贝的定义似乎有点问题?

### ISSUE THREAD

**Issue by Hasaki1997** [InterviewMap/InterviewMap#74]
浅拷贝是指a和b指向了同一块内存，所以修改其中任意的值，另一个值都会随之变化。

`Object.assign`和`(...)`算是不完全的深拷贝,但不能说是浅拷贝吧?

**Comment by KieSun** [comment]
通过什么来定义不完全的深拷贝？

**Comment by KieSun** [comment]
深拷贝就是两个不同的对象，改变任何一方都不会改变另一方。如果存在改变的情况那么就是浅拷贝，没有什么不完全的深拷贝。

**Comment by KieSun** [comment]
对于第一层来说确实是深拷贝了，但是第二层开始就不是了。所以对于多层对象来说，他就是浅拷贝。
