### ISSUE TITLE
node eventloop 举例问题

### ISSUE THREAD

**Issue by duziten** [InterviewMap/InterviewMap#81]
![image](https://user-images.githubusercontent.com/29852019/43115923-01654de0-8f38-11e8-9905-343669d12c40.png)

有时候是timer1,timer2,promise1,promise2;
有时候是timer1,promise1,timer2,promise2;
node v8.11.1

**Comment by KieSun** [comment]
@duziten 恩，浏览器中打印是固定的，node 中会有不同

**Comment by duziten** [comment]
这应该是event loop 初始化直接在timers阶段处理callback，还是进入poll阶段按顺序执行进入timers阶段执行有关吧

**Comment by SabinDiwan** [comment]
Oh sorry.im getting a point inthe end.thts is a result in simple language.i cant use any simpler code.i  dont know how much time you will waste to understand this question now.

**Comment by SabinDiwan** [comment]
Oh sorry.im getting a point inthe end.thts is a result in simple language.i cant use any simpler code.i  dont know how much time you will waste to understand this question now.
