### ISSUE TITLE
获取实例原型为什么不用Object.getPrototypeOf呢

### ISSUE THREAD

**Issue by pomelovico** [InterviewMap/InterviewMap#91]
我发现文章好多地方都提到__proto__属性，但这是非官方的属性吧，是各大浏览器自主实现的方便开发人员调试的属性，获取一个实例的原型用Object.getPrototypeOf不应该更好吗

**Comment by naihe138** [comment]
@pomelovico 虽然__proto__属性是非官方的属性。但是讲到原型和原型链的时候，就避免不了来解释这个，这个也称之为`原型指针`，是为了更好的去了解原型的思想。下面给你推荐一篇文章，你有时间可以去看一下呢。[http://huang-jerryc.com/2016/06/28/JavaScript%E5%8E%9F%E5%9E%8B%E4%B8%AD%E7%9A%84%E5%93%B2%E5%AD%A6%E6%80%9D%E6%83%B3/](http://huang-jerryc.com/2016/06/28/JavaScript%E5%8E%9F%E5%9E%8B%E4%B8%AD%E7%9A%84%E5%93%B2%E5%AD%A6%E6%80%9D%E6%83%B3/)
